---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: demo-messages
  namespace: kafka
  labels:
    strimzi.io/cluster: demo-kafka
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 604800000
